### ISSUE TITLE
Exporting worlds in WP v2.11.0 with build50 of this plugin fails

### ISSUE THREAD

**Issue by Grausiga** [OpenCubicChunks/WorldPainterSupportCC#12]
java.lang.NoSuchFieldError: selectedTiles
	at io.github.opencubicchunks.worldpainterplugin.CubicChunksWorldExporter.export(CubicChunksWorldExporter.java:36)
	at org.pepsoft.worldpainter.ExportProgressDialog$1.execute(ExportProgressDialog.java:149)
	at org.pepsoft.worldpainter.ExportProgressDialog$1.execute(ExportProgressDialog.java:136)
	at org.pepsoft.util.swing.MultiProgressComponent$1.run(MultiProgressComponent.java:91)

WorldPainter version: 2.11.0 (20220724220720)

java.version: 1.8.0_291
java.vendor: Oracle Corporation
java.vm.version: 25.291-b10
java.vm.vendor: Oracle Corporation
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
os.name: Windows 10
os.arch: amd64
os.version: 10.0

**Comment by Deepseasaltyfish** [comment]
I also meet the problem that the map can't be exported as occ world in the newer version

java.lang.NoSuchFieldError: selectedTiles
	at io.github.opencubicchunks.worldpainterplugin.CubicChunksWorldExporter.export(CubicChunksWorldExporter.java:36)
	at org.pepsoft.worldpainter.ExportProgressDialog$1.execute(ExportProgressDialog.java:149)
	at org.pepsoft.worldpainter.ExportProgressDialog$1.execute(ExportProgressDialog.java:136)
	at org.pepsoft.util.swing.MultiProgressComponent$1.run(MultiProgressComponent.java:91)

WorldPainter version: 2.12.0 (20220802170604)

java.version: 17.0.3.1
java.vendor: Oracle Corporation
java.vm.version: 17.0.3.1+2-LTS-6
java.vm.vendor: Oracle Corporation
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
os.name: Windows 10
os.arch: amd64
os.version: 10.0

Free memory: 206327920 bytes
Total memory size: 461373440 bytes
Max memory size: 14856224768 bytes

World name: Generated World
Platform: Cubic Chunks (1.10.2 - 1.12.2) (org.pepsoft.cubicchunks)
Seed: -43288290311739115
Bounds: -2, -2 => 2, 2
Height: 8388608
Number of tiles: 25
Layers in use: 
Border: null @ 62
Sub surface material: Stone Mix
Water height: 62

Operation: null
Radius: 50
Brush: Plateau Circle (radius=0, brushShape=CIRCLE, level=1.0)/Sine Circle (radius=7, brushShape=CIRCLE, level=1.0)
Level: 0.51/0.51
Zoom: 0
Hidden layers: [Biome]
