### ISSUE TITLE
Illegal argument exception: minHeight 0 when trying to export

### ISSUE THREAD

**Issue by ghost** [OpenCubicChunks/WorldPainterSupportCC#14]
This error occurs when I try to export my world (imported from a TIF heightmap)
`
java.lang.IllegalArgumentException: minHeight 0
	at org.pepsoft.worldpainter.plugins.BlockBasedPlatformProvider.createChunk(BlockBasedPlatformProvider.java:69)
	at org.pepsoft.worldpainter.exporting.WorldPainterChunkFactory.createChunk(WorldPainterChunkFactory.java:124)
	at org.pepsoft.worldpainter.exporting.WorldPainterChunkFactory.createChunk(WorldPainterChunkFactory.java:101)
	at org.pepsoft.worldpainter.exporting.AbstractWorldExporter.createChunk(AbstractWorldExporter.java:846)
	at org.pepsoft.worldpainter.exporting.AbstractWorldExporter.firstPass(AbstractWorldExporter.java:531)
	at org.pepsoft.worldpainter.exporting.AbstractWorldExporter.lambda$exportRegion$9(AbstractWorldExporter.java:776)
	at org.pepsoft.util.mdc.MDCUtils.doWithMdcContext(MDCUtils.java:59)
	at org.pepsoft.worldpainter.exporting.AbstractWorldExporter.exportRegion(AbstractWorldExporter.java:729)
	at org.pepsoft.worldpainter.exporting.AbstractWorldExporter.lambda$parallelExportRegions$2(AbstractWorldExporter.java:261)
	at org.pepsoft.util.mdc.MDCThreadPoolExecutor.lambda$wrap$0(MDCThreadPoolExecutor.java:55)

Diagnostic context:
	region.coords: java.awt.Point[x=2,y=1]

WorldPainter version: 2.18.4 (20230627210413)

java.version: 20
java.vendor: Oracle Corporation
java.vm.version: 20+36-2344
java.vm.vendor: Oracle Corporation
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
os.name: Windows 10
os.arch: amd64
os.version: 10.0
user.home: C:\Users\jasam
user.dir: C:\Program Files\WorldPainter
user.country: US
user.language: en

Free memory: 3209768360 bytes
Total memory size: 7373586432 bytes
Max memory size: 14277410816 bytes

World name: smppakrac2-v0
Platform: Cubic Chunks (1.10.2 - 1.12.2) (org.pepsoft.cubicchunks)
Seed: -7404336506295398071
Bounds: 0, 0 => 307, 107
Height: 1024
Number of tiles: 33264
Layers in use: Frost
Border: ENDLESS_BARRIER @ 0
Sub surface material: Stone Mix
Water height: 0

Operation: Spawn
Radius: 50
Brush: Plateau Circle (radius=0, brushShape=CIRCLE, level=1.0)/Sine Circle (radius=7, brushShape=CIRCLE, level=1.0)
Level: 0.51/0.51
Zoom: -4
Hidden layers: [Biome]
`

**Comment by SurvivorBob** [comment]
Root cause is API change in WorldPainter: https://github.com/Captain-Chaos/WorldPainter/commit/cdedbe99dcdaf98692db8f2a02ecf726f2a6f6e4#diff-2c4ceef0263041cef7c66126b5f645c65bca23aa64951112d8dc54816f756595

**Comment by Sylsatra** [comment]
> Root cause is API change in WorldPainter: [Captain-Chaos/WorldPainter@cdedbe9#diff-2c4ceef0263041cef7c66126b5f645c65bca23aa64951112d8dc54816f756595](https://github.com/Captain-Chaos/WorldPainter/commit/cdedbe99dcdaf98692db8f2a02ecf726f2a6f6e4#diff-2c4ceef0263041cef7c66126b5f645c65bca23aa64951112d8dc54816f756595)

what should we do to fix this API change?

**Comment by Sylsatra** [comment]
I managed to fix the error, do this step by step:
Step 1: Uninstall the current version of Worldpainter.
Step 2: Install Worldpainter 2.7.18 from this [link](https://www.worldpainter.net/trac/wiki/OldVersions).
Step 3: Install Java 8 from this [link](https://www.java.com/en/download/).
Step 4: Press Win + R, type regedit, and hit Enter.
![Screenshot 2024-12-08 092801](https://github.com/user-attachments/assets/8336f62c-18cd-4782-92f2-d1d600cc2325)
Step 5: In the Registry Editor, navigate to HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\JDK\"your java version ( for me it is 17.0.11)"
![Screenshot 2024-12-08 092847](https://github.com/user-attachments/assets/6366fc39-0978-400a-a8dd-7d5233ef07d7)
![Screenshot 2024-12-08 092918](https://github.com/user-attachments/assets/434f47e3-ad05-4736-829f-8f5f689194ac)
![Screenshot 2024-12-08 092938](https://github.com/user-attachments/assets/1755ce93-6b70-413f-a6b3-90aa4a851897)
![Screenshot 2024-12-08 092952](https://github.com/user-attachments/assets/e0cc0349-d4e3-4b77-8420-b2b0511b851a)
Step 6: Double click the JavaHome file inside your java version folder (which is in the JDK folder)
Step 7: Change the JavaHome value to the path of your java 8, for me it is C:\Program Files\Java\jre1.8.0_431.

I managed to fix this issue thanks to the Reddit post, all credit goes to him!
![Screenshot 2024-12-08 093153](https://github.com/user-attachments/assets/f30bd5ee-c4a0-4d76-aa6d-4f963b385a8f)
If you'd like to revert the change, please follow the steps but change java 8.
