### ISSUE TITLE
WP crashed when exporting CC world

### ISSUE THREAD

**Issue by kaixu631** [OpenCubicChunks/WorldPainterSupportCC#7]
**Crash report:**

java.lang.RuntimeException: Duplicate key TAG_Compound: 1 entries
{
   TAG_Compound("Level"): 12 entries
   {
      TAG_Byte("isSurfaceTracked"): 0
      TAG_Compound("LightingInfo"): 2 entries
      {
         TAG_Int_Array("LastHeightMap"): (deleted. The string is too long...)
         TAG_Byte("EdgeNeedSkyLightUpdate"): 0
      }
      TAG_Byte("populated"): 0
      TAG_List("TileEntities"): 0 entries of type TAG_Compound
      {
      }
      TAG_List("Entities"): 0 entries of type TAG_Compound
      {
      }
      TAG_List("Sections"): 1 entries of type TAG_Compound
      {
         TAG_Compound: 4 entries
         {
            TAG_Byte_Array("BlockLight"): (deleted. The string is too long... All zero.)
            TAG_Byte_Array("Data"): (deleted. The string is too long...)
            TAG_Byte_Array("Blocks"): (deleted. The string is too long...  One layer of 07(bedrock), and the remaining is 01(stone).)
            TAG_Byte_Array("SkyLight"): (deleted. The string is too long...  All zero.)
         }
      }
      TAG_Byte("v"): 1
      TAG_Int("x"): 49
      TAG_Byte("initLightDone"): 0
      TAG_Int("y"): 0
      TAG_Byte("fullyPopulated"): 1
      TAG_Int("z"): 31
   }
} (object: cobblestone at 785,496,223)
	at org.pepsoft.worldpainter.layers.exporters.WPObjectExporter.renderObject(WPObjectExporter.java:199)
	at org.pepsoft.worldpainter.layers.exporters.WPObjectExporter.renderObject(WPObjectExporter.java:61)
	at org.pepsoft.worldpainter.layers.exporters.WPObjectExporter$WPObjectFixup.fixup(WPObjectExporter.java:517)
	at org.pepsoft.worldpainter.exporting.AbstractWorldExporter.performFixups(AbstractWorldExporter.java:941)
	at org.pepsoft.worldpainter.exporting.AbstractWorldExporter.performFixupsIfNecessary(AbstractWorldExporter.java:916)
	at org.pepsoft.worldpainter.exporting.AbstractWorldExporter.lambda$parallelExportRegions$0(AbstractWorldExporter.java:305)
	at org.pepsoft.util.mdc.MDCThreadPoolExecutor.lambda$wrap$0(MDCThreadPoolExecutor.java:55)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(null:-1)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(null:-1)
	at java.lang.Thread.run(null:-1)

Root cause:
java.lang.IllegalStateException: Duplicate key TAG_Compound: 1 entries
{
   TAG_Compound("Level"): 12 entries
   {
      TAG_Byte("isSurfaceTracked"): 0
      TAG_Compound("LightingInfo"): 2 entries
      {
         TAG_Int_Array("LastHeightMap"): (deleted. The string is too long...)
         TAG_Byte("EdgeNeedSkyLightUpdate"): 0
      }
      TAG_Byte("populated"): 0
      TAG_List("TileEntities"): 0 entries of type TAG_Compound
      {
      }
      TAG_List("Entities"): 0 entries of type TAG_Compound
      {
      }
      TAG_List("Sections"): 1 entries of type TAG_Compound
      {
         TAG_Compound: 4 entries
         {
            TAG_Byte_Array("BlockLight"): (deleted. The string is too long... All zero.)
            TAG_Byte_Array("Data"): (deleted. The string is too long...)
            TAG_Byte_Array("Blocks"): (deleted. The string is too long...)
            TAG_Byte_Array("SkyLight"): (deleted. The string is too long...)
         }
      }
      TAG_Byte("v"): 1
      TAG_Int("x"): 49
      TAG_Byte("initLightDone"): 0
      TAG_Int("y"): 0
      TAG_Byte("fullyPopulated"): 1
      TAG_Int("z"): 31
   }
}
	at java.util.stream.Collectors.lambda$throwingMerger$0(null:-1)
	at java.util.HashMap.merge(null:-1)
	at java.util.stream.Collectors.lambda$toMap$58(null:-1)
	at java.util.stream.ReduceOps$3ReducingSink.accept(null:-1)
	at java.util.stream.ReferencePipeline$3$1.accept(null:-1)

WorldPainter version: 2.7.17 (20200809193939)

java.version: 1.8.0_181
java.vendor: Oracle Corporation
java.vm.version: 25.181-b13
java.vm.vendor: Oracle Corporation
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
os.name: Windows 10
os.arch: amd64
os.version: 10.0
user.home: C:\Users\45165
user.dir: S:\WorldPainter
user.country: CN
user.language: zh

Free memory: 3418124720 bytes
Total memory size: 10517741568 bytes
Max memory size: 28510257152 bytes

World name: Practice11 v3
Seed: -6048179798112847380
Bounds: 0, 0 => 31, 31
Height: 8388608
Number of tiles: 1024
Layers in use: 地表灌木1, 苔石块, 灰化土灌木, 细矮树, 橡树叶灌木丛, 粗细混交矮树, 高细树 (矮版本), 地表树叶, 碎石, 高细树 (高版本), 山沟灌木, 堆积坡灌木, 粗土覆盖层, 雨林树叶灌木丛, 山顶灌木, 极矮树, River, 生物群系, 密集矮植被, 岩上草 **(note: they are just object layers)**
Border: VOID @ 0
Sub surface material: Stone Mix
Water height: 0

Operation: null
Radius: 50
Brush: Plateau Circle (radius=0, brushShape=CIRCLE, level=1.0)/Sine Circle (radius=0, brushShape=CIRCLE, level=1.0)
Level: 0.51/0.51
Zoom: 0
Hidden layers: [Biome]

**Using latest version of CC plugin.
No problem found when I export in normal format (roughly the same terrain, exactly the same layers, but vanilla world)**

**Please help, this bug is driving me mad...**

**Comment by kaixu631** [comment]
**Here's how to fix the bug:**
**In the class** io.github.opencubicchunks.worldpainterplugin.CubicChunkStore**, in the method** loadChunk, **you need to modify the** .collect **line in the definition of** cubeTags, **inserting** (key1, key2) -> key1 **to prevent duplicate keys. This is not where the problem origiates, but indeed it fixes the bug.**

**Comment by Niko-sk2x** [comment]
This looks like a bug in how the plugin handles exporting into a world that already exists. The root cause is probably here <https://github.com/OpenCubicChunks/WorldPainterSupportCC/blob/9bbc7325860f199e751a2791e68b2b867fd3bbe8/src/main/java/io/github/opencubicchunks/worldpainterplugin/CubicChunkStore.java#L149>
I will look into it. In the meantime, avoid exporting into an already existing world.

**Comment by Grausiga** [comment]
> **Here's how to fix the bug:** **In the class** io.github.opencubicchunks.worldpainterplugin.CubicChunkStore**, in the method** loadChunk, **you need to modify the** .collect **line in the definition of** cubeTags, **inserting** (key1, key2) -> key1 **to prevent duplicate keys. This is not where the problem origiates, but indeed it fixes the bug.**

Has this ever been fixed? I have the same problem now
